version: "3.9"

services:
  srl_service:
    build: ./srl_service
    container_name: srl_service
    ports:
      - "${SRL_PORT:-8000}:8000"              # FastAPI exposed on localhost:8000
    volumes:
      - ./srl_service:/app       # Mount code for live reload (dev)
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py --host 0.0.0.0 --port 8000

  lsb_service:
    build: ./lsb
    container_name: lsb_service
    privileged: true
    volumes:
      - ./lsb:/app
      - /etc/wireguard:/etc/wireguard
    environment:
      - PYTHONUNBUFFERED=1
    ports:
    - "${LSB_PORT:-5000}:5000"       #
    depends_on:
      - srl_service
    command: python /app/main.py --host 0.0.0.0 --port 5000 --srl-host ${SRL_CONNECT_HOST:-srl_service} --srl-port ${SRL_CONNECT_PORT:-8000}
    # Uncomment if you need VPN-level networking access
    # network_mode: "host"

  lsb_static:
    image: python:3.12-slim
    container_name: lsb_static
    working_dir: /app
    volumes:
      - ./lsb:/app
    ports:
      - "${LSB_STATIC_PORT:-8080}:8080"
    depends_on:
      - srl_service
    command: python -m http.server 8080

