version: "3.9"

services:
  fastapi:
    build: ./srl_service
    container_name: stub_server
    ports:
      - "8000:8000"         # Map local port 8000 â†’ container port 8000
    volumes:
      - ./srl_service:/app             # Mount current folder for live code updates (dev only)
    environment:
      - PYTHONUNBUFFERED=1  # Ensures logs show up immediately in the console
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # The --reload flag restarts the server automatically on code changes
