services:
  srl_service:
    build: ./srl_service
    container_name: srl_service
    ports:
      - "${SRL_PORT:-8000}:8000" # FastAPI exposed on localhost:8000
    volumes:
      - ./srl_service:/app       # Mount code for live reload (dev)
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py --host 0.0.0.0 --port ${SRL_CONNECT_PORT:-8000}

  lsb_python:
    build: ./lsb
    container_name: lsb_python
    privileged: true
    volumes:
      - ./lsb:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
    - "${LSB_PORT:-5000}:5000"       #
    depends_on:
      - srl_service
    command: python /app/main.py --host 0.0.0.0 --port 5000 --srl-host ${SRL_CONNECT_HOST:-srl_service} --srl-port ${SRL_CONNECT_PORT:-8000}
    # Uncomment if you need VPN-level networking access
    # network_mode: "host"

  lsb_html:
    image: python:3.12-slim
    container_name: lsb_html
    working_dir: /app
    volumes:
      - ./lsb:/app
    ports:
      - "${LSB_HTTP_PORT:-5080}:5080"
    depends_on:
      - srl_service
    command: python -m http.server ${LSB_HTTP_PORT:-5080}

  lsb_php:
    image: php:8.2-cli
    container_name: lsb_php
    working_dir: /app
    volumes:
      - ./lsb:/app
    network_mode: "host"
    #ports:
    #  - "${LSB_PHP_PORT:-5090}:5090"
    #  - "${SRL_PORT:-8000}:8000"
    depends_on:
      - srl_service
    command: php -S 0.0.0.0:${LSB_PHP_PORT:-5090}
    

